# -*- coding: utf-8 -*-
"""2.11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJ0n76Q4DbpMZKVYI7WDwLy9yra9c4e9
"""

!pip install scikit-fuzzy

import skfuzzy as fuzz
from skfuzzy import control as ctrl
import numpy as np

rdist = ctrl.Antecedent(np.arange(0 , 50.1, 1), 'ride distance')
rdist['short'] = fuzz.trimf(rdist.universe, [0,0,5])
rdist['medium'] = fuzz.trimf(rdist.universe, [0,5,13])
rdist['long'] = fuzz.trimf(rdist.universe, [5,13,50])
rdist['very long'] = fuzz.trimf(rdist.universe, [13,50,50])
rdist.view()

traffic = ctrl.Antecedent(np.arange(0, 1.001, 0.01), 'traffic condition')
traffic['low'] = fuzz.trimf(traffic.universe, [0,0,0.45])
traffic['medium'] = fuzz.trimf(traffic.universe, [0,0.45,1])
traffic['high'] = fuzz.trimf(traffic.universe, [0.45,1,1])
traffic.view()

demand = ctrl.Antecedent(np.arange(0, 1.001, 0.01), 'demand level')
demand['low'] = fuzz.trimf(demand.universe, [0,0,0.45])
demand['medium'] = fuzz.trimf(demand.universe, [0,0.45,1])
demand['high'] = fuzz.trimf(demand.universe, [0.45,1,1])
demand.view()

weather = ctrl.Antecedent(np.arange(0,10.1, 0.1), 'weather condition')
weather['good'] = fuzz.trimf(weather.universe, [0,0,5])
weather['moderate'] = fuzz.trimf(weather.universe, [0,5,10])
weather['bad'] = fuzz.trimf(weather.universe, [5,10,10])
weather.view()

rating = ctrl.Antecedent(np.arange(1, 5.1, 0.5), 'customer rating')
rating['poor'] = fuzz.trimf(rating.universe, [1,1,3])
rating['average'] = fuzz.trimf(rating.universe, [1,3,5])
rating['good'] = fuzz.trimf(rating.universe, [3,5,5])
rating.view()

rpunc = ctrl.Antecedent(np.arange(0, 1.001, 0.01), 'ride punctuality')
rpunc['late'] = fuzz.trimf(rpunc.universe, [0,0,0.6])
rpunc['ontime'] = fuzz.trimf(rpunc.universe, [0,0.6,1])
rpunc['early'] = fuzz.trimf(rpunc.universe, [0.6,1,1])
rpunc.view()

price = ctrl.Consequent(np.arange(0, 150.1, 1), 'price')
price['low'] = fuzz.trimf(price.universe, [0,0,40])
price['medium'] = fuzz.trimf(price.universe, [0,40,75])
price['high'] = fuzz.trimf(price.universe, [40,75,150])
price['very high'] = fuzz.trimf(price.universe, [75,150,150])
price.view()

point = ctrl.Consequent(np.arange(0, 10.1, 0.1), 'rewards point')
point['none'] = fuzz.trimf(point.universe, [0,0,3])
point['few'] = fuzz.trimf(point.universe, [0,3,6.5])
point['moderate'] = fuzz.trimf(point.universe, [3,6.5,10])
point['high'] = fuzz.trimf(point.universe, [6.5,10,10])
point.view()

rule1=ctrl.Rule(rdist['short']&traffic['low']&demand['low'], price['low'])
rule2=ctrl.Rule(rdist['short']&traffic['medium']&demand['high'], price['medium'])
rule3=ctrl.Rule(rdist['medium']&traffic['high']&demand['high'], price['high'])
rule4=ctrl.Rule(rdist['long']&traffic['medium']&weather['good'], price['medium'])
rule5=ctrl.Rule(rdist['long']&traffic['high']&weather['bad'], price['very high'])
rule6=ctrl.Rule(rdist['very long']&traffic['high']&demand['high'], price['very high'])
rule7=ctrl.Rule(rdist['medium']&traffic['low']&demand['low'], price['medium'])
rule8=ctrl.Rule(rdist['short']&traffic['high']&weather['bad'], price['high'])
rule9=ctrl.Rule(rdist['very long']&weather['bad'], price['very high'])
rule10=ctrl.Rule(rdist['medium']&traffic['medium']&weather['moderate'], price['medium'])
rule11=ctrl.Rule(rating['good']&rpunc['early'], point['high'])
rule12=ctrl.Rule(rating['average']&rpunc['ontime'], point['moderate'])
rule13=ctrl.Rule(rating['poor']&rpunc['late'], point['none'])
rule14=ctrl.Rule(rdist['medium']&traffic['medium']&rating['good'], point['moderate'])
rule15=ctrl.Rule(rdist['long']&traffic['high']&rpunc['ontime'], point['high'])
rule16=ctrl.Rule(rating['poor']&rpunc['late'], point['none'])
rule17=ctrl.Rule(rdist['very long']&rating['good']&weather['bad'], point['few'])
rule18=ctrl.Rule(rdist['short']&rating['average']&rpunc['ontime'], point['few'])
rule19=ctrl.Rule(rdist['long']&traffic['high']&rpunc['late'], point['few'])
rule20=ctrl.Rule(rdist['medium']&rating['good']&weather['moderate'], point['moderate'])

pricing_ctrl=ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5,rule6,rule7,rule8,rule9,rule10,rule11,rule12,rule13,rule14,rule15,rule16,rule17,rule18,rule19,rule20])
pricing = ctrl.ControlSystemSimulation(pricing_ctrl)
pricing.input['ride distance']=37
pricing.input['traffic condition']=0.7
pricing.input['demand level']=0.5
pricing.input['weather condition']=7
pricing.input['customer rating']=4.8
pricing.input['ride punctuality']=0.7
pricing.compute()
print('số tiền của chuyến đi là:',pricing.output['price'])
print('điểm thưởng cho khách hàng là:',pricing.output['rewards point'])
price.view(sim=pricing)
point.view(sim=pricing)

