# -*- coding: utf-8 -*-
"""2.12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYrmzjSrMDate54b-kHkfos3l5lF_QPA
"""

!pip install scikit-fuzzy

import skfuzzy as fuzz
from skfuzzy import control as ctrl
import numpy as np

store_rating = ctrl.Antecedent(np.arange(0 , 10.1, 0.01), 'store rating')
store_rating['low'] = fuzz.trimf(store_rating.universe, [0,0,4.25])
store_rating['medium'] = fuzz.trimf(store_rating.universe, [0,4.25,10])
store_rating['high'] = fuzz.trimf(store_rating.universe, [4.25,10,10])
store_rating.view()

sales_volume = ctrl.Antecedent(np.arange(0 , 100.1, 1), 'sales volume')
sales_volume['low'] = fuzz.trimf(sales_volume.universe, [0,0,50])
sales_volume['medium'] = fuzz.trimf(sales_volume.universe, [25,50,75])
sales_volume['high'] = fuzz.trimf(sales_volume.universe, [50,100,100])
sales_volume.view()

profit_margin = ctrl.Antecedent(np.arange(0 , 100.1, 1), 'profit margin')
profit_margin['low'] = fuzz.trimf(profit_margin.universe, [0,0,50])
profit_margin['medium'] = fuzz.trimf(profit_margin.universe, [25,50,75])
profit_margin['high'] = fuzz.trimf(profit_margin.universe, [50,100,100])
profit_margin.view()

seasonal_event = ctrl.Antecedent(np.arange(0 , 100.1, 1), 'seasonal event')
seasonal_event['none'] = fuzz.trimf(seasonal_event.universe, [0,0,40])
seasonal_event['moderate'] = fuzz.trimf(seasonal_event.universe, [0,40,100])
seasonal_event['high'] = fuzz.trimf(seasonal_event.universe, [40,100,100])
seasonal_event.view()

competitor_discount = ctrl.Antecedent(np.arange(0 , 100.1, 1), 'competitor discount')
competitor_discount['low'] = fuzz.trimf(competitor_discount.universe, [0,0,50])
competitor_discount['medium'] = fuzz.trimf(competitor_discount.universe, [25,50,75])
competitor_discount['high'] = fuzz.trimf(competitor_discount.universe, [50,100,100])
competitor_discount.view()

percent = ctrl.Consequent(np.arange(0, 70.1, 0.1), 'output')
percent['verylow'] = fuzz.trimf(percent.universe, [0,0,5])
percent['low'] = fuzz.trimf(percent.universe, [5,7.5,10])
percent['medium'] = fuzz.trimf(percent.universe, [10,15,20])
percent['high'] = fuzz.trimf(percent.universe, [20,30,40])
percent['veryhigh'] = fuzz.trimf(percent.universe, [40,55,70])
percent.view()

rule1 = ctrl.Rule(store_rating['high'] & sales_volume['high'] & profit_margin['high'], percent['verylow'])
rule2 = ctrl.Rule(store_rating['low'] & sales_volume['low'] & profit_margin['high'], percent['high'])
rule3 = ctrl.Rule(seasonal_event['high'] & competitor_discount['high'], percent['veryhigh'])
rule4 = ctrl.Rule(store_rating['medium'] & sales_volume['medium'] & profit_margin['medium'], percent['medium'])
rule5 = ctrl.Rule(competitor_discount['low'] & profit_margin['low'] & sales_volume['high'], percent['verylow'])
rule6 = ctrl.Rule(store_rating['low'] & seasonal_event['none'], percent['medium'])
rule7 = ctrl.Rule(sales_volume['low'] & profit_margin['low'], percent['veryhigh'])

discount_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7])
discount_sim = ctrl.ControlSystemSimulation(discount_ctrl)
discount_sim.input['store rating'] = 7
discount_sim.input['sales volume'] = 50
discount_sim.input['profit margin'] = 20
discount_sim.input['seasonal event'] = 80
discount_sim.input['competitor discount'] = 80
discount_sim.compute()
print(f"Phần trăm chiết khấu dự kiến: {discount_sim.output['output']:.2f}%")
percent.view(sim=discount_sim)

