# -*- coding: utf-8 -*-
"""2.13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBYvzeoKAg2125p-wJhm9oD8VSFjDHpl
"""

!pip install scikit-fuzzy

import skfuzzy as fuzz
from skfuzzy import control as ctrl
import numpy as np

product_demand = ctrl.Antecedent(np.arange(0 , 100.1, 1), 'product demand')
product_demand['low'] = fuzz.trimf(product_demand.universe, [0,0,50])
product_demand['medium'] = fuzz.trimf(product_demand.universe, [25,50,75])
product_demand['high'] = fuzz.trimf(product_demand.universe, [50,100,100])
product_demand.view()

competitor_pricing_pressure = ctrl.Antecedent(np.arange(0 , 100.1, 1), 'competitor pricing pressure')
competitor_pricing_pressure['low'] = fuzz.trimf(competitor_pricing_pressure.universe, [0,0,50])
competitor_pricing_pressure['medium'] = fuzz.trimf(competitor_pricing_pressure.universe, [25,50,75])
competitor_pricing_pressure['high'] = fuzz.trimf(competitor_pricing_pressure.universe, [50,100,100])
competitor_pricing_pressure.view()

store_reputation = ctrl.Antecedent(np.arange(0 , 5.1, 0.01), 'store reputation')
store_reputation['low'] = fuzz.trimf(store_reputation.universe, [0,0,4])
store_reputation['medium'] = fuzz.trimf(store_reputation.universe, [4,4.25,4.5])
store_reputation['high'] = fuzz.trimf(store_reputation.universe, [4.5,5,5])
store_reputation.view()

profit_margin = ctrl.Antecedent(np.arange(0 , 100.1, 1), 'profit margin')
profit_margin['low'] = fuzz.trimf(profit_margin.universe, [0,0,50])
profit_margin['medium'] = fuzz.trimf(profit_margin.universe, [25,50,75])
profit_margin['high'] = fuzz.trimf(profit_margin.universe, [50,100,100])
profit_margin.view()

seasonal_demand = ctrl.Antecedent(np.arange(0 , 100.1, 1), 'seasonal demand')
seasonal_demand['none'] = fuzz.trimf(seasonal_demand.universe, [0,0,40])
seasonal_demand['moderate'] = fuzz.trimf(seasonal_demand.universe, [0,40,100])
seasonal_demand['high'] = fuzz.trimf(seasonal_demand.universe, [40,100,100])
seasonal_demand.view()

percent = ctrl.Consequent(np.arange(0, 70.1, 0.1), 'output')
percent['verylow'] = fuzz.trimf(percent.universe, [0,0,5])
percent['low'] = fuzz.trimf(percent.universe, [5,7.5,10])
percent['medium'] = fuzz.trimf(percent.universe, [10,15,20])
percent['high'] = fuzz.trimf(percent.universe, [20,30,40])
percent['veryhigh'] = fuzz.trimf(percent.universe, [40,55,70])
percent.view()

rule1 = ctrl.Rule(product_demand['high'] & competitor_pricing_pressure['low'] & profit_margin['low'], percent['verylow'])
rule2 = ctrl.Rule(product_demand['low'] & competitor_pricing_pressure['high'] & profit_margin['high'], percent['high'])
rule3 = ctrl.Rule(store_reputation['high'] & profit_margin['medium'] & seasonal_demand['high'], percent['medium'])
rule4 = ctrl.Rule(competitor_pricing_pressure['high'] & seasonal_demand['high'] & profit_margin['high'], percent['veryhigh'])
rule5 = ctrl.Rule(store_reputation['low'] & product_demand['medium'] & profit_margin['low'], percent['medium'])
rule6 = ctrl.Rule(product_demand['high'] & seasonal_demand['none'] & competitor_pricing_pressure['low'], percent['verylow'])
rule7 = ctrl.Rule(profit_margin['high'] & competitor_pricing_pressure['medium'] & seasonal_demand['moderate'], percent['medium'])

percenting_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7])
percenting = ctrl.ControlSystemSimulation(percenting_ctrl)
percenting.input['product demand'] = 90
percenting.input['competitor pricing pressure'] = 50
percenting.input['store reputation'] = 4.2
percenting.input['profit margin'] = 85
percenting.input['seasonal demand'] = 95
percenting.compute()
print(f"Mức giảm giá cho đồng hồ xa xỉ: {percenting.output['output']:.2f}%")
percent.view(sim=percenting)

