# -*- coding: utf-8 -*-
"""2.14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13KsjDWjfmvBLwu9G05zbU4ABhH0EPfS8
"""

!pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

density = ctrl.Antecedent(np.arange(0, 100.1, 1), 'order_density')
urgency = ctrl.Antecedent(np.arange(0, 100.1, 1), 'delivery_urgency')
load    = ctrl.Antecedent(np.arange(0, 100.1, 1), 'driver_load')
traffic = ctrl.Antecedent(np.arange(0, 60.1, 1),  'traffic_conditions')
profit  = ctrl.Antecedent(np.arange(0, 500.1, 1), 'profit_per_delivery')
combine  = ctrl.Consequent(np.arange(1, 10.1, 0.1), 'orders_to_combine')
priority = ctrl.Consequent(np.arange(0, 100.1, 1), 'delivery_priority')

density['low']    = fuzz.trimf(density.universe, [0, 0, 40])
density['medium'] = fuzz.trimf(density.universe, [30, 50, 70])
density['high']   = fuzz.trimf(density.universe, [60, 100, 100])

urgency['low']    = fuzz.trimf(urgency.universe, [0, 0, 30])
urgency['medium'] = fuzz.trimf(urgency.universe, [20, 50, 80])
urgency['high']   = fuzz.trimf(urgency.universe, [70, 100, 100])

load['low']    = fuzz.trimf(load.universe, [0, 0, 40])
load['medium'] = fuzz.trimf(load.universe, [30, 50, 70])
load['high']   = fuzz.trimf(load.universe, [60, 100, 100])

profit['low']    = fuzz.trimf(profit.universe, [0, 0, 150])
profit['medium'] = fuzz.trimf(profit.universe, [100, 250, 400])
profit['high']   = fuzz.trimf(profit.universe, [350, 500, 500])

traffic['low_speed'] = fuzz.trimf(traffic.universe, [0, 0, 25])
traffic['mid_speed'] = fuzz.trimf(traffic.universe, [20, 30, 40])
traffic['high_speed'] = fuzz.trimf(traffic.universe, [35, 60, 60])

combine['few']    = fuzz.trimf(combine.universe, [1, 1, 4])
combine['some']   = fuzz.trimf(combine.universe, [3, 5, 7])
combine['many']   = fuzz.trimf(combine.universe, [6, 10, 10])

priority['low']    = fuzz.trimf(priority.universe, [0, 0, 40])
priority['medium'] = fuzz.trimf(priority.universe, [30, 50, 70])
priority['high']   = fuzz.trimf(priority.universe, [60, 100, 100])

rules = [
    ctrl.Rule(density['high'] & load['low'] & traffic['high_speed'], combine['many']),
    ctrl.Rule(density['medium'] & traffic['low_speed'] & urgency['medium'], combine['some']),
    ctrl.Rule(load['high'] & density['high'] & profit['medium'], combine['some']),
    ctrl.Rule(density['low'] & urgency['high'] & traffic['low_speed'], combine['few']),
    ctrl.Rule(profit['high'] & urgency['high'] & traffic['low_speed'], combine['few']),
    ctrl.Rule(urgency['high'] & profit['high'], priority['high']),
    ctrl.Rule(urgency['medium'] & traffic['mid_speed'], priority['medium']),
    ctrl.Rule(urgency['low'] & density['high'] & profit['low'], priority['low'])
]

delivery_ctrl = ctrl.ControlSystem(rules)
delivering  = ctrl.ControlSystemSimulation(delivery_ctrl)

delivering.input['order_density'] = 85
delivering.input['delivery_urgency'] = 80
delivering.input['driver_load'] = 20
delivering.input['traffic_conditions'] = 40
delivering.input['profit_per_delivery'] = 400

delivering.compute()

print(f"Số lượng đơn hàng cần kết hợp: {delivering.output['orders_to_combine']:.2f}")
print(f"Mức độ ưu tiên giao hàng: {delivering.output['delivery_priority']:.2f}%")

